name:                AdventOfCode2021
version:             0.1.0.0
github:              "Periodic/AdventOfCode2021"
license:             MIT
author:              "Drew Haven"
maintainer:          "drew.haven@gmail.com"
copyright:           "2021 Drew Haven"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/periodic/AdventOfCode2021#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13
- text >= 1.0
- containers >= 0.6
- vector >= 0.12
- lens >= 4.0
- extra >= 1.7

ghc-options:
- -O
- -rtsopts

default-extensions:
- OverloadedStrings
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- BangPatterns
- GADTs
- LambdaCase
- RankNTypes
- TupleSections

library:
  source-dirs: lib
  dependencies:
  - optparse-applicative >= 0.15
  - criterion >= 1.5.7

executables:
  Day01:
    main:                Main.hs
    source-dirs:         src/Day01
    dependencies:
      - AdventOfCode2021

  Day02:
    main:                Main.hs
    source-dirs:         src/Day02
    dependencies:
      - AdventOfCode2021
      - linear >= 1.21

  Day03:
    main:                Main.hs
    source-dirs:         src/Day03
    dependencies:
      - AdventOfCode2021

  Day04:
    main:                Main.hs
    source-dirs:         src/Day04
    dependencies:
      - AdventOfCode2021