name:                AdventOfCode2021
version:             0.1.0.0
github:              "Periodic/AdventOfCode2021"
license:             MIT
author:              "Drew Haven"
maintainer:          "drew.haven@gmail.com"
copyright:           "2021 Drew Haven"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/periodic/AdventOfCode2021#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13
- text >= 1.0
- containers >= 0.6
- vector >= 0.12
- lens >= 4.0
- extra >= 1.7
- mtl >= 2.2
- linear >= 1.21
- hspec

ghc-options:
- -O
- -rtsopts

default-extensions:
- OverloadedStrings
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- RecordWildCards
- BangPatterns
- GADTs
- LambdaCase
- RankNTypes
- TupleSections

library:
  source-dirs: lib
  dependencies:
  - optparse-applicative >= 0.15
  - criterion >= 1.5.7

executables:
  Day01:
    main:                Main.hs
    source-dirs:         src/Day01
    dependencies:
      - AdventOfCode2021

  Day02:
    main:                Main.hs
    source-dirs:         src/Day02
    dependencies:
      - AdventOfCode2021

  Day03:
    main:                Main.hs
    source-dirs:         src/Day03
    dependencies:
      - AdventOfCode2021

  Day04:
    main:                Main.hs
    source-dirs:         src/Day04
    dependencies:
      - AdventOfCode2021
      - array

  Day05:
    main:                Main.hs
    source-dirs:         src/Day05
    dependencies:
      - AdventOfCode2021
      - array

  Day06:
    main:                Main.hs
    source-dirs:         src/Day06
    dependencies:
      - AdventOfCode2021
      - hmatrix

  Day07:
    main:                Main.hs
    source-dirs:         src/Day07
    dependencies:
      - AdventOfCode2021

  Day08:
    main:                Main.hs
    source-dirs:         src/Day08
    dependencies:
      - AdventOfCode2021

  Day09:
    main:                Main.hs
    source-dirs:         src/Day09
    dependencies:
      - AdventOfCode2021

  Day10:
    main:                Main.hs
    source-dirs:         src/Day10
    dependencies:
      - AdventOfCode2021

  Day11:
    main:                Main.hs
    source-dirs:         src/Day11
    dependencies:
      - AdventOfCode2021
      - array

  Day12:
    main:                Main.hs
    source-dirs:         src/Day12
    dependencies:
      - AdventOfCode2021

  Day13:
    main:                Main.hs
    source-dirs:         src/Day13
    dependencies:
      - AdventOfCode2021

  Day14:
    main:                Main.hs
    source-dirs:         src/Day14
    dependencies:
      - AdventOfCode2021

  Day15:
    main:                Main.hs
    source-dirs:         src/Day15
    dependencies:
      - AdventOfCode2021
      - pqueue

  Day16:
    main:                Main.hs
    source-dirs:         src/Day16
    dependencies:
      - AdventOfCode2021

  Day17:
    main:                Main.hs
    source-dirs:         src/Day17
    dependencies:
      - AdventOfCode2021

  Day18:
    main:                Main.hs
    source-dirs:         src/Day18
    dependencies:
      - AdventOfCode2021

  Day19:
    main:                Main.hs
    source-dirs:         src/Day19
    dependencies:
      - AdventOfCode2021

  Day20:
    main:                Main.hs
    source-dirs:         src/Day20
    dependencies:
      - AdventOfCode2021
      - array

  Day21:
    main:                Main.hs
    source-dirs:         src/Day21
    dependencies:
      - AdventOfCode2021

  Day22:
    main:                Main.hs
    source-dirs:         src/Day22
    dependencies:
      - AdventOfCode2021

  Day23:
    main:                Main.hs
    source-dirs:         src/Day23
    dependencies:
      - AdventOfCode2021

  Day24:
    main:                Main.hs
    source-dirs:         src/Day24
    dependencies:
      - AdventOfCode2021
